{
 "title": "metrics-server-core",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Total requests",
   "type": "stat",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "game_core_requests_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Memory",
   "type": "stat",
   "gridPos": { "h": 9, "w": 7, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes / 1048576",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Gorutines",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 0 },
   "targets": [
    { "expr": "go_goroutines", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 10, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by(method) (rate(game_core_request_duration_seconds_sum[5m])) \r\n/\r\nsum by(method) (rate(game_core_request_duration_seconds_count[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 14, "x": 10, "y": 9 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[5m])\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "sum by(code) (rate(game_core_requests_total{code=~\"4..|5..\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}